// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cloud_backend.Data;

#nullable disable

namespace cloud_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250416061547_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("cloud_backend.Models.Customer_User", b =>
                {
                    b.Property<Guid>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("credentialId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("verificationToken")
                        .HasColumnType("longtext");

                    b.HasKey("customerId");

                    b.HasIndex("credentialId")
                        .IsUnique();

                    b.ToTable("customer_user");
                });

            modelBuilder.Entity("cloud_backend.Models.Manufacturing_Request", b =>
                {
                    b.Property<Guid>("requestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("cost")
                        .HasColumnType("double");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("productId")
                        .HasColumnType("char(36)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("requestId");

                    b.HasIndex("productId")
                        .IsUnique();

                    b.ToTable("manufacturing_request");
                });

            modelBuilder.Entity("cloud_backend.Models.Order_Items", b =>
                {
                    b.Property<Guid>("orderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("discountPercentage")
                        .HasColumnType("int");

                    b.Property<Guid>("orderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("productId")
                        .HasColumnType("char(36)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<double>("unitPrice")
                        .HasColumnType("double");

                    b.HasKey("orderItemId");

                    b.HasIndex("orderId");

                    b.HasIndex("productId")
                        .IsUnique();

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("cloud_backend.Models.Orders", b =>
                {
                    b.Property<Guid>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("credentialId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("discountPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fulfilledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("orderId");

                    b.HasIndex("credentialId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("cloud_backend.Models.Products", b =>
                {
                    b.Property<Guid>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("cost")
                        .HasColumnType("double");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<int>("discountPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("model")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.Property<int>("soldQuantity")
                        .HasColumnType("int");

                    b.Property<int>("stockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("productId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("cloud_backend.Models.Quotation_Items", b =>
                {
                    b.Property<Guid>("quotationItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("discountPercentage")
                        .HasColumnType("int");

                    b.Property<Guid>("productId")
                        .HasColumnType("char(36)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("quotationId")
                        .HasColumnType("char(36)");

                    b.Property<double>("unitPrice")
                        .HasColumnType("double");

                    b.HasKey("quotationItemId");

                    b.HasIndex("productId")
                        .IsUnique();

                    b.HasIndex("quotationId");

                    b.ToTable("quotation_items");
                });

            modelBuilder.Entity("cloud_backend.Models.Quotation_Request", b =>
                {
                    b.Property<Guid>("quotationRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<Guid>("storeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("quotationRequestId");

                    b.HasIndex("storeId");

                    b.ToTable("quotation_request");
                });

            modelBuilder.Entity("cloud_backend.Models.Quotation_Request_Items", b =>
                {
                    b.Property<Guid>("quotationRequestItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("discountPercentage")
                        .HasColumnType("int");

                    b.Property<Guid>("productId")
                        .HasColumnType("char(36)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("quotationRequestId")
                        .HasColumnType("char(36)");

                    b.Property<double>("unitPrice")
                        .HasColumnType("double");

                    b.HasKey("quotationRequestItemId");

                    b.HasIndex("productId")
                        .IsUnique();

                    b.HasIndex("quotationRequestId");

                    b.ToTable("quotation_request_items");
                });

            modelBuilder.Entity("cloud_backend.Models.Quotations", b =>
                {
                    b.Property<Guid>("quotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("discountPercentage")
                        .HasColumnType("int");

                    b.Property<Guid?>("orderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<Guid>("storeId")
                        .HasColumnType("char(36)");

                    b.Property<double>("totalAmount")
                        .HasColumnType("double");

                    b.Property<int>("totalQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("quotationId");

                    b.HasIndex("orderId")
                        .IsUnique();

                    b.HasIndex("storeId");

                    b.ToTable("quotations");
                });

            modelBuilder.Entity("cloud_backend.Models.Receipts", b =>
                {
                    b.Property<Guid>("receiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("credentialId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("orderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("paymentMethod")
                        .HasColumnType("int");

                    b.Property<int?>("paymentType")
                        .HasColumnType("int");

                    b.HasKey("receiptId");

                    b.HasIndex("credentialId");

                    b.HasIndex("orderId")
                        .IsUnique();

                    b.ToTable("receipts");
                });

            modelBuilder.Entity("cloud_backend.Models.Staff_User", b =>
                {
                    b.Property<Guid>("staffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("credentialId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("staffId");

                    b.HasIndex("credentialId")
                        .IsUnique();

                    b.ToTable("staff_user");
                });

            modelBuilder.Entity("cloud_backend.Models.Store_User", b =>
                {
                    b.Property<Guid>("storeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("credentialId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("storeId");

                    b.HasIndex("credentialId")
                        .IsUnique();

                    b.ToTable("store_user");
                });

            modelBuilder.Entity("cloud_backend.Models.User_Credentials", b =>
                {
                    b.Property<Guid>("credentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("contactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastLogOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("credentialId");

                    b.ToTable("user_credentials");
                });

            modelBuilder.Entity("cloud_backend.Models.Customer_User", b =>
                {
                    b.HasOne("cloud_backend.Models.User_Credentials", "User_Credential")
                        .WithOne("Customer_User")
                        .HasForeignKey("cloud_backend.Models.Customer_User", "credentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User_Credential");
                });

            modelBuilder.Entity("cloud_backend.Models.Manufacturing_Request", b =>
                {
                    b.HasOne("cloud_backend.Models.Products", "Products")
                        .WithOne("Manufacturing_Request")
                        .HasForeignKey("cloud_backend.Models.Manufacturing_Request", "productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("cloud_backend.Models.Order_Items", b =>
                {
                    b.HasOne("cloud_backend.Models.Orders", "Orders")
                        .WithMany("OrderItems")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cloud_backend.Models.Products", "Product")
                        .WithOne("Order_Items")
                        .HasForeignKey("cloud_backend.Models.Order_Items", "productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("cloud_backend.Models.Orders", b =>
                {
                    b.HasOne("cloud_backend.Models.User_Credentials", "User_Credential")
                        .WithMany("Orders")
                        .HasForeignKey("credentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User_Credential");
                });

            modelBuilder.Entity("cloud_backend.Models.Quotation_Items", b =>
                {
                    b.HasOne("cloud_backend.Models.Products", "Products")
                        .WithOne("Quotation_Items")
                        .HasForeignKey("cloud_backend.Models.Quotation_Items", "productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cloud_backend.Models.Quotations", "Quotations")
                        .WithMany("quotationItems")
                        .HasForeignKey("quotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("Quotations");
                });

            modelBuilder.Entity("cloud_backend.Models.Quotation_Request", b =>
                {
                    b.HasOne("cloud_backend.Models.Store_User", "Store_User")
                        .WithMany("Quotation_Requests")
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store_User");
                });

            modelBuilder.Entity("cloud_backend.Models.Quotation_Request_Items", b =>
                {
                    b.HasOne("cloud_backend.Models.Products", "Products")
                        .WithOne("Quotation_Request_Items")
                        .HasForeignKey("cloud_backend.Models.Quotation_Request_Items", "productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cloud_backend.Models.Quotation_Request", "Quotation_Request")
                        .WithMany("quotationRequestItems")
                        .HasForeignKey("quotationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("Quotation_Request");
                });

            modelBuilder.Entity("cloud_backend.Models.Quotations", b =>
                {
                    b.HasOne("cloud_backend.Models.Orders", "Orders")
                        .WithOne("Quotations")
                        .HasForeignKey("cloud_backend.Models.Quotations", "orderId");

                    b.HasOne("cloud_backend.Models.Store_User", "Store_User")
                        .WithMany("Quotations")
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Store_User");
                });

            modelBuilder.Entity("cloud_backend.Models.Receipts", b =>
                {
                    b.HasOne("cloud_backend.Models.User_Credentials", "User_Credentials")
                        .WithMany("Receipts")
                        .HasForeignKey("credentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cloud_backend.Models.Orders", "Orders")
                        .WithOne("Receipts")
                        .HasForeignKey("cloud_backend.Models.Receipts", "orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("User_Credentials");
                });

            modelBuilder.Entity("cloud_backend.Models.Staff_User", b =>
                {
                    b.HasOne("cloud_backend.Models.User_Credentials", "User_Credential")
                        .WithOne("Factory_User")
                        .HasForeignKey("cloud_backend.Models.Staff_User", "credentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User_Credential");
                });

            modelBuilder.Entity("cloud_backend.Models.Store_User", b =>
                {
                    b.HasOne("cloud_backend.Models.User_Credentials", "User_Credential")
                        .WithOne("Store_User")
                        .HasForeignKey("cloud_backend.Models.Store_User", "credentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User_Credential");
                });

            modelBuilder.Entity("cloud_backend.Models.Orders", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Quotations");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("cloud_backend.Models.Products", b =>
                {
                    b.Navigation("Manufacturing_Request");

                    b.Navigation("Order_Items");

                    b.Navigation("Quotation_Items");

                    b.Navigation("Quotation_Request_Items");
                });

            modelBuilder.Entity("cloud_backend.Models.Quotation_Request", b =>
                {
                    b.Navigation("quotationRequestItems");
                });

            modelBuilder.Entity("cloud_backend.Models.Quotations", b =>
                {
                    b.Navigation("quotationItems");
                });

            modelBuilder.Entity("cloud_backend.Models.Store_User", b =>
                {
                    b.Navigation("Quotation_Requests");

                    b.Navigation("Quotations");
                });

            modelBuilder.Entity("cloud_backend.Models.User_Credentials", b =>
                {
                    b.Navigation("Customer_User");

                    b.Navigation("Factory_User");

                    b.Navigation("Orders");

                    b.Navigation("Receipts");

                    b.Navigation("Store_User");
                });
#pragma warning restore 612, 618
        }
    }
}
